"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Row = Record<string, string | number | null | boolean>;
type IntakeData = { batches: Row[]; selectedBatchId: string; rows: Row[]; events: Row[]; controls: { maximumRows: number; maximumBytes: number; originalRetained: boolean; approvalRequired: boolean; automaticApply: boolean } };
const statusLabel: Record<string, string> = { UPLOADED: "업로드", VALIDATED: "검증 완료", NEEDS_REVIEW: "검토 필요", SUBMITTED: "결재 중", APPROVED: "승인 완료", REJECTED: "반려", APPLIED: "반영 완료", FAILED: "실패", VALID: "정상", INVALID: "제외 필요", CREATE: "신규", UPDATE: "수정", SKIP: "제외" };
const dateTime = (value: number) => value ? new Date(value).toLocaleString("ko-KR", { dateStyle: "short", timeStyle: "short" }) : "";

export default function DataIntakeWorkspace({ sources }: { sources: Row[] }) {
  const [data, setData] = useState<IntakeData | null>(null); const [sourceId, setSourceId] = useState("hiworks-employees"); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const selected = useMemo(() => data?.batches.find((batch) => batch.id === data.selectedBatchId) ?? null, [data]);
  function fetchData(batchId = "") { return fetch(`/api/data-intake${batchId ? `?batchId=${encodeURIComponent(batchId)}` : ""}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "수집 원장을 불러오지 못했습니다."); setData(payload); }); }
  useEffect(() => { let cancelled = false; fetch("/api/data-intake", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "수집 원장을 불러오지 못했습니다."); if (!cancelled) setData(payload); }).catch((caught) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "수집 원장을 불러오지 못했습니다."); }); return () => { cancelled = true; }; }, []);
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; setBusy("UPLOAD"); setError(""); setNotice(""); const body = new FormData(); body.set("sourceId", sourceId); body.set("file", file); try { const response = await fetch("/api/data-intake", { method: "POST", body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "파일을 수집하지 못했습니다."); setData(payload); setFile(null); setNotice("원본을 보관하고 행 단위 미리보기를 생성했습니다."); } catch (caught) { setError(caught instanceof Error ? caught.message : "파일을 수집하지 못했습니다."); } finally { setBusy(""); } }
  async function mutate(action: string, extra: Record<string, unknown> = {}) { if (!selected) return; setBusy(action); setError(""); setNotice(""); try { const response = await fetch("/api/data-intake", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, batchId: selected.id, ...extra }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "수집 작업을 완료하지 못했습니다."); setData(payload); setNotice(action === "SUBMIT" ? "전자결재에 제출했습니다." : action === "APPLY" ? "승인된 행을 업무 원장에 반영했습니다." : "행 처리방식을 저장했습니다."); } catch (caught) { setError(caught instanceof Error ? caught.message : "수집 작업을 완료하지 못했습니다."); } finally { setBusy(""); } }
  return <section className="data-governance-section data-intake-section"><header><div data-korean-heading><h3>파일 수집·승인·반영</h3><span>원본을 보관한 뒤 500행까지 미리보기·검증하고, 결재 완료 후에만 명시적으로 반영합니다.</span></div><div className="data-intake-template-links"><a href="/api/data-intake?template=employees">인사 표준양식</a><a href="/api/data-intake?template=payroll">급여 표준양식</a></div></header>
    <form className="data-intake-upload" onSubmit={upload}><label>원천<select value={sourceId} onChange={(event) => setSourceId(event.target.value)}>{sources.filter((source) => Boolean(source.enabled)).map((source) => <option key={String(source.id)} value={String(source.id)}>{String(source.name)}</option>)}</select></label><label>CSV·JSON·XLSX<input type="file" accept=".csv,.json,.xlsx,text/csv,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><button type="submit" disabled={!file || Boolean(busy)}>{busy === "UPLOAD" ? "검증 중…" : "원본 보관·검증"}</button><p>동일 원천·동일 파일 체크섬은 재등록되지 않습니다. 자동 반영은 수행하지 않습니다.</p></form>
    {error && <div className="data-governance-message error">{error}</div>}{notice && <div className="data-governance-message">{notice}</div>}
    <div className="data-intake-layout"><aside><header><strong>수집 배치</strong><button type="button" onClick={() => void fetchData(data?.selectedBatchId)}>새로고침</button></header>{data?.batches.map((batch) => <button type="button" className={batch.id === data.selectedBatchId ? "active" : ""} key={String(batch.id)} onClick={() => void fetchData(String(batch.id))}><em>{statusLabel[String(batch.status)] ?? String(batch.status)}</em><strong>{String(batch.file_name)}</strong><small>{String(batch.source_name)} · {dateTime(Number(batch.created_at))}</small></button>)}{!data?.batches.length && <p>등록된 수집 파일이 없습니다.</p>}</aside>
      <div className="data-intake-preview">{selected ? <><div className="data-intake-batch-head"><div><em>{statusLabel[String(selected.status)] ?? String(selected.status)}</em><h4>{String(selected.file_name)}</h4><p>{String(selected.source_name)} · SHA-256 {String(selected.file_sha256).slice(0, 14)}…</p></div><dl><div><dt>전체</dt><dd>{Number(selected.total_rows)}행</dd></div><div><dt>정상</dt><dd>{Number(selected.valid_rows)}행</dd></div><div><dt>오류·중복</dt><dd>{Number(selected.invalid_rows)}행</dd></div><div><dt>예정</dt><dd>신규 {Number(selected.create_rows)} · 수정 {Number(selected.update_rows)} · 제외 {Number(selected.skip_rows)}</dd></div></dl><div className="data-intake-actions"><a href={`/api/data-intake?downloadId=${encodeURIComponent(String(selected.id))}`}>원본</a>{["VALIDATED", "NEEDS_REVIEW"].includes(String(selected.status)) && <button type="button" disabled={Boolean(busy)} onClick={() => void mutate("SUBMIT")}>결재 제출</button>}{String(selected.status) === "APPROVED" && selected.apply_supported && <button type="button" disabled={Boolean(busy)} onClick={() => void mutate("APPLY")}>승인본 반영</button>}{String(selected.status) === "APPROVED" && !selected.apply_supported && <span>업무 매핑 확정 대기</span>}</div></div>
        <div className="data-intake-table-wrap"><table><thead><tr><th>행</th><th>검증</th><th>식별키</th><th>처리</th><th>정규화 미리보기</th><th>확인사항</th></tr></thead><tbody>{data?.rows.map((row) => <tr key={String(row.id)} className={String(row.validation_status).toLowerCase()}><td>{Number(row.row_number)}</td><td><em>{statusLabel[String(row.validation_status)]}</em></td><td>{String(row.identity_key || "매핑 전")}</td><td><select disabled={!['VALIDATED','NEEDS_REVIEW'].includes(String(selected.status))} value={String(row.proposed_action)} onChange={(event) => void mutate("SET_ROW_ACTION", { rowId: row.id, proposedAction: event.target.value })}><option value="CREATE">신규</option><option value="UPDATE">수정</option><option value="SKIP">제외</option></select></td><td><code>{String(row.normalized_json).slice(0, 220)}</code></td><td>{(() => { try { const issues = JSON.parse(String(row.issues_json)) as string[]; return issues.join(" · ") || "없음"; } catch { return "확인 필요"; } })()}</td></tr>)}</tbody></table></div>
        <div className="data-intake-events"><strong>처리 이력</strong>{data?.events.map((event) => <p key={String(event.id)}><em>{String(event.action)}</em><span>{String(event.note)}</span><time>{dateTime(Number(event.created_at))}</time></p>)}</div></> : <div className="data-governance-empty">수집 배치를 선택하면 검증 결과와 행별 처리 예정값을 확인할 수 있습니다.</div>}</div></div>
  </section>;
}
