"use client";

import { useEffect, useState } from "react";
import DataIntakeWorkspace from "./data-intake-workspace";
import FinanceImportMappingWorkspace from "./finance-import-mapping-workspace";
import FinancePostingWorkspace from "./finance-posting-workspace";

type Row = Record<string, string | number | null>;
type Payload = { summary: { totalSources: number; healthySources: number; attentionSources: number; openHighExceptions: number }; sources: Row[]; runs: Row[]; exceptions: Row[]; employees: Row[]; controls: { externalFetch: boolean; automaticOverwrite: boolean; automaticDelete: boolean; evaluationLabel: string } };
const labels: Record<string, string> = { SUCCEEDED: "정상", NEEDS_REVIEW: "검토 필요", FAILED: "실패", RUNNING: "실행 중", OPEN: "미처리", IN_REVIEW: "검토 중", RESOLVED: "해결", ACCEPTED_RISK: "위험 수용", CRITICAL: "위험", HIGH: "높음", NORMAL: "보통", LOW: "낮음" };
const dateTime = (value: number | null) => value ? new Date(value).toLocaleString("ko-KR", { dateStyle: "short", timeStyle: "short" }) : "기록 없음";

export default function DataIntegrationWorkspace() {
  const [data, setData] = useState<Payload | null>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { let cancelled = false; fetch("/api/data-integration", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "연동 원장을 불러오지 못했습니다."); if (!cancelled) setData(payload); }).catch((caught) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "연동 원장을 불러오지 못했습니다."); }); return () => { cancelled = true; }; }, []);
  async function mutate(action: string, extra: Record<string, unknown> = {}) { setBusy(action + String(extra.sourceId ?? extra.runId ?? extra.exceptionId ?? "")); setError(""); setNotice(""); try { const response = await fetch("/api/data-integration", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...extra }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "작업을 완료하지 못했습니다."); setData(payload); setNotice(action === "REFRESH_ALL" ? "모든 활성 원천의 현재 ERP 스냅샷을 검증했습니다." : "연동 원장을 갱신했습니다."); } catch (caught) { setError(caught instanceof Error ? caught.message : "작업을 완료하지 못했습니다."); } finally { setBusy(""); } }
  function review(exception: Row, action: "RESOLVE_EXCEPTION" | "ACCEPT_RISK") { const note = window.prompt(action === "RESOLVE_EXCEPTION" ? "해결 근거를 5자 이상 입력해 주세요." : "위험 수용 사유를 5자 이상 입력해 주세요.", ""); if (note == null) return; void mutate(action, { exceptionId: exception.id, note }); }
  if (!data) return <div className="data-governance-loading">연동·대사 원장을 불러오는 중입니다.</div>;
  return <div className="data-governance-body data-integration-body">
    {error && <div className="data-governance-message error">{error}</div>}{notice && <div className="data-governance-message">{notice}</div>}
    <div className="data-integration-boundary"><div><strong>현재 ERP 스냅샷 검증</strong><span>원천 연결을 새로 호출하지 않고, 배포된 원본과 D1 원장을 다시 대사합니다.</span></div><ul><li>외부 조회 없음</li><li>자동 덮어쓰기 없음</li><li>자동 삭제 없음</li></ul><button disabled={Boolean(busy)} type="button" onClick={() => void mutate("REFRESH_ALL")}>{busy === "REFRESH_ALL" ? "검증 중…" : "전체 재검증"}</button></div>
    <section className="data-governance-summary"><article><span>등록 원천</span><strong>{data.summary.totalSources}<em>개</em></strong><small>재무·HR 통합</small></article><article className="healthy"><span>정상</span><strong>{data.summary.healthySources}<em>개</em></strong><small>최근 실행 기준</small></article><article className="attention"><span>확인 필요</span><strong>{data.summary.attentionSources}<em>개</em></strong><small>재검증 또는 검토</small></article><article className={data.summary.openHighExceptions ? "critical" : "healthy"}><span>고위험 미처리</span><strong>{data.summary.openHighExceptions}<em>건</em></strong><small>사람의 판단 필요</small></article></section>
    <DataIntakeWorkspace sources={data.sources} />
    <FinanceImportMappingWorkspace />
    <FinancePostingWorkspace />
    <section className="data-governance-section"><header><div data-korean-heading><h3>연동 원천 등록부</h3><span>주기·기준일·책임자와 마지막 검증 상태를 한곳에서 관리합니다.</span></div></header><div className="data-integration-sources">{data.sources.map((source) => <article key={String(source.id)}><div><em>{String(source.category)}</em><strong>{String(source.name)}</strong><small>{String(source.system_type)} · {String(source.connection_mode)} · {String(source.scope)}</small><p>{String(source.description)}</p></div><dl><div><dt>상태</dt><dd className={String(source.last_status ?? "").toLowerCase()}>{labels[String(source.last_status)] ?? "미검증"}</dd></div><div><dt>기준일</dt><dd>{String(source.last_snapshot_date ?? "없음")}</dd></div><div><dt>미처리 예외</dt><dd>{Number(source.open_exception_count ?? 0)}건</dd></div></dl><label>담당자<select value={String(source.owner_employee_id ?? "")} onChange={(event) => void mutate("UPDATE_SOURCE", { sourceId: source.id, expectedCadence: source.expected_cadence, freshnessHours: source.freshness_hours, enabled: Boolean(source.enabled), ownerEmployeeId: event.target.value })}><option value="">미지정</option>{data.employees.map((employee) => <option value={String(employee.employee_id)} key={String(employee.employee_id)}>{String(employee.name)} · {String(employee.department)}</option>)}</select></label><button disabled={Boolean(busy)} type="button" onClick={() => void mutate("EVALUATE_SOURCE", { sourceId: source.id })}>스냅샷 검증</button></article>)}</div></section>
    <section className="data-governance-section"><header><div data-korean-heading><h3>예외 검토함</h3><span>자동 검증은 후보만 만들고, 해결·위험 수용에는 관리자 근거를 남깁니다.</span></div></header><div className="data-integration-exceptions">{data.exceptions.map((exception) => <article key={String(exception.id)} className={String(exception.severity).toLowerCase()}><em>{labels[String(exception.severity)] ?? String(exception.severity)}</em><div><strong>{String(exception.title)}</strong><small>{String(exception.exception_type)} · {labels[String(exception.status)] ?? String(exception.status)}</small><p>{String(exception.detail)}</p><span>{String(exception.suggested_action)}</span>{exception.resolution_note && <i>검토기록: {String(exception.resolution_note)}</i>}</div><label>담당자<select disabled={!['OPEN','IN_REVIEW'].includes(String(exception.status))} value={String(exception.owner_employee_id ?? "")} onChange={(event) => void mutate("ASSIGN_EXCEPTION", { exceptionId: exception.id, ownerEmployeeId: event.target.value })}><option value="">미지정</option>{data.employees.map((employee) => <option value={String(employee.employee_id)} key={String(employee.employee_id)}>{String(employee.name)}</option>)}</select></label>{['OPEN','IN_REVIEW'].includes(String(exception.status)) && <div className="data-integration-actions"><button onClick={() => review(exception, "RESOLVE_EXCEPTION")}>해결</button><button onClick={() => review(exception, "ACCEPT_RISK")}>위험 수용</button></div>}</article>)}{!data.exceptions.length && <div className="data-governance-empty">등록된 예외가 없습니다. 전체 재검증을 실행해 현재 상태를 확인하세요.</div>}</div></section>
    <section className="data-governance-section"><header><div data-korean-heading><h3>실행·재시도 원장</h3><span>동일 체크섬은 중복 실행하지 않으며 재시도는 원 실행을 연결해 보존합니다.</span></div></header><div className="data-integration-runs">{data.runs.map((run) => <article key={String(run.id)}><em className={String(run.status).toLowerCase()}>{labels[String(run.status)] ?? String(run.status)}</em><div><strong>{data.sources.find((source) => source.id === run.source_id)?.name ?? run.source}</strong><small>{String(run.snapshot_date)} · {dateTime(Number(run.created_at))} · 수신 {Number(run.received_count ?? run.record_count)} / 대상 {Number(run.record_count)} / 검토 {Number(run.review_count ?? 0)}</small><code>SHA {String(run.source_checksum || "legacy").slice(0, 14)}{run.retry_of_run_id ? ` · 재시도 원본 ${String(run.retry_of_run_id).slice(0, 8)}` : ""}</code></div><button disabled={Boolean(busy)} type="button" onClick={() => void mutate("RETRY_RUN", { runId: run.id })}>재시도</button></article>)}</div></section>
  </div>;
}
