"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Row = Record<string, string | number | null | boolean | string[] | Record<string, string>>;
type Field = { key: string; label: string; required: boolean; aliases: string[] };
type MappingData = {
  batches: Row[]; mappingSets: Row[]; validations: Row[]; selectedSetId: string; selectedBatchId: string;
  rules: Row[]; events: Row[]; canonicalRows: Row[];
  masters: { accounts: Row[]; partners: Row[]; banks: Row[]; organizations: Row[] };
  fieldDefinitions: Record<string, Field[]>;
  controls: { exactMatchOnly: boolean; approvalRequired: boolean; directPosting: boolean; balanceToleranceKrw: number };
};

const typeLabels: Record<string, string> = { JOURNAL: "분개장", TRIAL_BALANCE: "합계잔액시산표", BANK_TRANSACTION: "은행거래" };
const statusLabels: Record<string, string> = { DRAFT: "초안", SUBMITTED: "결재 중", ACTIVE: "활성", REJECTED: "반려", SUPERSEDED: "이전 버전", PASSED: "검증 통과", BLOCKED: "차단" };
const dimensionLabels: Record<string, string> = { ACCOUNT: "계정과목", PARTNER: "거래처", DEPARTMENT: "부서", BANK_ACCOUNT: "은행계좌" };
const time = (value: unknown) => value ? new Date(Number(value)).toLocaleString("ko-KR", { dateStyle: "short", timeStyle: "short" }) : "—";
const won = (value: unknown) => `${Number(value ?? 0).toLocaleString("ko-KR")}원`;

export default function FinanceImportMappingWorkspace() {
  const [data, setData] = useState<MappingData | null>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [batchId, setBatchId] = useState(""); const [mappingSetId, setMappingSetId] = useState(""); const [dataType, setDataType] = useState("JOURNAL"); const [name, setName] = useState(""); const [fieldMapping, setFieldMapping] = useState<Record<string, string>>({});
  const [rule, setRule] = useState({ dimensionType: "ACCOUNT", sourceKey: "", targetId: "" });
  const selectedBatch = useMemo(() => data?.batches.find((row) => String(row.id) === batchId) ?? null, [data, batchId]);
  const selectedSet = useMemo(() => data?.mappingSets.find((row) => String(row.id) === mappingSetId) ?? null, [data, mappingSetId]);
  const latestValidation = useMemo(() => data?.validations.find((row) => String(row.batch_id) === batchId) ?? null, [data, batchId]);

  async function load(nextSet = mappingSetId, nextBatch = batchId) {
    const query = new URLSearchParams(); if (nextSet) query.set("mappingSetId", nextSet); if (nextBatch) query.set("batchId", nextBatch);
    const response = await fetch(`/api/finance/import-mappings?${query}`, { cache: "no-store" }); const payload = await response.json() as MappingData & { error?: string }; if (!response.ok) throw new Error(payload.error || "재무 매핑을 불러오지 못했습니다.");
    setData(payload); const resolvedSet = nextSet || payload.selectedSetId; const resolvedBatch = nextBatch || payload.selectedBatchId; setMappingSetId(resolvedSet); setBatchId(resolvedBatch);
    const current = payload.mappingSets.find((item) => String(item.id) === resolvedSet); if (current) { setName(String(current.name)); setFieldMapping((current.fieldMapping as Record<string, string>) ?? {}); setDataType(String(current.data_type)); }
  }
  useEffect(() => { let cancelled = false; fetch("/api/finance/import-mappings", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as MappingData & { error?: string }; if (!response.ok) throw new Error(payload.error || "재무 매핑을 불러오지 못했습니다."); if (!cancelled) { setData(payload); setMappingSetId(payload.selectedSetId); setBatchId(payload.selectedBatchId); const current = payload.mappingSets.find((item) => String(item.id) === payload.selectedSetId); if (current) { setName(String(current.name)); setFieldMapping((current.fieldMapping as Record<string, string>) ?? {}); setDataType(String(current.data_type)); } } }).catch((caught) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "재무 매핑을 불러오지 못했습니다."); }); return () => { cancelled = true; }; }, []);
  async function mutate(action: string, extra: Record<string, unknown> = {}) { setBusy(action); setError(""); setNotice(""); try { const response = await fetch("/api/finance/import-mappings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, mappingSetId, batchId, ...extra }) }); const payload = await response.json() as MappingData & { error?: string }; if (!response.ok) throw new Error(payload.error || "매핑 작업을 완료하지 못했습니다."); setData(payload); const nextSet = payload.selectedSetId || mappingSetId; setMappingSetId(nextSet); const current = payload.mappingSets.find((item) => String(item.id) === nextSet); if (current) { setName(String(current.name)); setFieldMapping((current.fieldMapping as Record<string, string>) ?? {}); setDataType(String(current.data_type)); } setNotice(action === "SUBMIT_SET" ? "매핑 세트를 전자결재에 제출했습니다." : action === "VALIDATE_BATCH" ? "활성 매핑으로 파일을 재검증했습니다." : "매핑 변경사항을 저장했습니다."); } catch (caught) { setError(caught instanceof Error ? caught.message : "매핑 작업을 완료하지 못했습니다."); } finally { setBusy(""); } }
  async function createDraft(event: FormEvent) { event.preventDefault(); await mutate("CREATE_DRAFT", { dataType, name }); }
  function chooseSet(id: string) { setMappingSetId(id); void load(id, batchId).catch((caught) => setError(caught instanceof Error ? caught.message : "매핑 세트를 불러오지 못했습니다.")); }
  function chooseBatch(id: string) { setBatchId(id); void load(mappingSetId, id).catch((caught) => setError(caught instanceof Error ? caught.message : "수집 배치를 불러오지 못했습니다.")); }
  const headers = Array.isArray(selectedBatch?.headers) ? selectedBatch.headers as string[] : [];
  const fields = selectedSet ? data?.fieldDefinitions[String(selectedSet.data_type)] ?? [] : [];
  const targets = rule.dimensionType === "ACCOUNT" ? data?.masters.accounts ?? [] : rule.dimensionType === "PARTNER" ? data?.masters.partners ?? [] : rule.dimensionType === "BANK_ACCOUNT" ? data?.masters.banks ?? [] : data?.masters.organizations ?? [];
  const targetLabel = (row: Row) => rule.dimensionType === "ACCOUNT" ? `${row.code} · ${row.name}` : rule.dimensionType === "PARTNER" ? String(row.canonical_name) : rule.dimensionType === "BANK_ACCOUNT" ? `${row.account_name} · ${row.last4} · GL ${row.gl_account_code || "미연결"}` : String(row.name);

  return <section className="data-governance-section finance-import-mapping"><header><div data-korean-heading><h3>재무 파일 매핑·균형검증</h3><span>정확 일치 또는 승인된 규칙만 사용하며, 차대변 1원 차이도 검증을 통과하지 못합니다.</span></div><div className="finance-import-control-tags"><em>자동 유사매칭 없음</em><em>직접 전기 없음</em><em>결재 후 활성</em></div></header>
    {error && <div className="data-governance-message error">{error}</div>}{notice && <div className="data-governance-message">{notice}</div>}
    <div className="finance-import-top-grid"><form onSubmit={createDraft}><strong>1. 수집 배치와 자료유형</strong><label>재무 파일<select value={batchId} onChange={(event) => chooseBatch(event.target.value)}><option value="">선택</option>{data?.batches.map((row) => <option key={String(row.id)} value={String(row.id)}>{String(row.file_name)} · {String(row.source_name)}</option>)}</select></label><label>자료유형<select value={dataType} onChange={(event) => setDataType(event.target.value)}>{Object.entries(typeLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>매핑명<input value={name} onChange={(event) => setName(event.target.value)} placeholder="예: 2025 이카운트 분개장" /></label><button disabled={!batchId || Boolean(busy)}>새 버전 초안 만들기</button></form>
      <div><strong>2. 매핑 버전</strong><div className="finance-import-set-list">{data?.mappingSets.map((row) => <button type="button" className={String(row.id) === mappingSetId ? "active" : ""} key={String(row.id)} onClick={() => chooseSet(String(row.id))}><em>{statusLabels[String(row.status)] ?? row.status}</em><span>{String(row.name)}</span><small>{typeLabels[String(row.data_type)]} · v{Number(row.version)}</small></button>)}{!data?.mappingSets.length && <p>등록된 재무 매핑이 없습니다.</p>}</div></div>
      <div><strong>3. 최근 검증</strong>{latestValidation ? <article className={`finance-import-validation ${String(latestValidation.status).toLowerCase()}`}><em>{statusLabels[String(latestValidation.status)]}</em><b>{Number(latestValidation.valid_count)}/{Number(latestValidation.row_count)}행 정상</b><span>차변 {won(latestValidation.total_debit)} · 대변 {won(latestValidation.total_credit)}</span><span>차이 {won(latestValidation.difference_amount)}</span><small>{time(latestValidation.created_at)}</small></article> : <p className="finance-import-empty">선택한 배치의 검증 이력이 없습니다.</p>}</div></div>
    {selectedSet && <div className="finance-import-editor"><section><header><div><em>{statusLabels[String(selectedSet.status)]}</em><h4>{String(selectedSet.name)}</h4><span>{String(selectedSet.source_name)} · {typeLabels[String(selectedSet.data_type)]} · 버전 {Number(selectedSet.version)}</span></div>{String(selectedSet.status) === "ACTIVE" && <button type="button" disabled={!batchId || Boolean(busy)} onClick={() => void mutate("VALIDATE_BATCH")}>선택 파일 재검증</button>}</header>
      <div className="finance-import-field-grid">{fields.map((field) => <label key={field.key}><span>{field.label}{field.required && <b>*</b>}</span><select disabled={String(selectedSet.status) !== "DRAFT"} value={fieldMapping[field.key] ?? ""} onChange={(event) => setFieldMapping({ ...fieldMapping, [field.key]: event.target.value })}><option value="">연결 안 함</option>{headers.map((header) => <option value={header} key={header}>{header}</option>)}</select></label>)}</div>
      <div className="finance-import-editor-actions"><button type="button" disabled={String(selectedSet.status) !== "DRAFT" || Boolean(busy)} onClick={() => void mutate("SAVE_DRAFT", { name, fieldMapping })}>열 매핑 저장</button><button type="button" className="primary" disabled={String(selectedSet.status) !== "DRAFT" || Boolean(busy)} onClick={() => void mutate("SUBMIT_SET")}>활성화 결재 제출</button><span>승인 전에는 검증 업무에 사용되지 않습니다.</span></div></section>
      <section><header><div data-korean-heading><h4>표준 마스터 연결 규칙</h4><span>계정·거래처·부서·은행계좌를 정확한 대상에 수동 연결합니다.</span></div></header>
        <div className="finance-import-rule-form"><label>차원<select disabled={String(selectedSet.status) !== "DRAFT"} value={rule.dimensionType} onChange={(event) => setRule({ dimensionType: event.target.value, sourceKey: "", targetId: "" })}>{Object.entries(dimensionLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>원천 값<input disabled={String(selectedSet.status) !== "DRAFT"} value={rule.sourceKey} onChange={(event) => setRule({ ...rule, sourceKey: event.target.value })} placeholder="파일에 표시된 값 그대로" /></label><label>표준 대상<select disabled={String(selectedSet.status) !== "DRAFT"} value={rule.targetId} onChange={(event) => setRule({ ...rule, targetId: event.target.value })}><option value="">선택</option>{targets.map((row) => <option key={String(row.id ?? row.organization_id)} value={String(row.id ?? row.organization_id)}>{targetLabel(row)}</option>)}</select></label><button type="button" disabled={String(selectedSet.status) !== "DRAFT" || !rule.sourceKey || !rule.targetId || Boolean(busy)} onClick={() => void mutate("UPSERT_RULE", { ...rule, sourceLabel: rule.sourceKey })}>규칙 저장</button></div>
        <div className="finance-import-rule-list"><div><span>차원</span><span>원천</span><span>표준 대상</span><span>방식</span><span></span></div>{data?.rules.map((row) => <div key={String(row.id)}><em>{dimensionLabels[String(row.dimension_type)]}</em><strong>{String(row.source_label)}</strong><span>{String(row.target_code)} {String(row.target_label)}</span><small>수동·정확</small><button type="button" disabled={String(selectedSet.status) !== "DRAFT" || Boolean(busy)} onClick={() => void mutate("DELETE_RULE", { ruleId: row.id })}>삭제</button></div>)}{!data?.rules.length && <p>추가 매핑 규칙이 없습니다. 활성 마스터와 정확히 같은 코드·명칭은 별도 규칙 없이 연결됩니다.</p>}</div>
      </section></div>}
    {data?.canonicalRows.length ? <div className="finance-import-canonical"><header><div data-korean-heading><h4>최근 정규화 결과</h4><span>운영 총계정원장이 아닌 검증용 스테이징입니다.</span></div></header><div><table><thead><tr><th>행</th><th>상태</th><th>기록키</th><th>표준화 결과</th><th>확인사항</th></tr></thead><tbody>{data.canonicalRows.map((row) => <tr key={String(row.id)}><td>{Number(row.row_number)}</td><td><em>{String(row.validation_status) === "VALID" ? "정상" : "차단"}</em></td><td>{String(row.record_key || "—")}</td><td><code>{String(row.canonical_json).slice(0, 260)}</code></td><td>{(() => { try { return (JSON.parse(String(row.issues_json)) as string[]).join(" · ") || "없음"; } catch { return "확인 필요"; } })()}</td></tr>)}</tbody></table></div></div> : null}
  </section>;
}
