"use client";

import { useEffect, useMemo, useState } from "react";

type Row = Record<string, string | number | null>;
type PostingData = { candidates: Row[]; batches: Row[]; selectedBatchId: string; vouchers: Row[]; lines: Row[]; events: Row[]; taxCodes: Row[]; closedPeriods: string[]; controls: Record<string, unknown> };
const statusLabels: Record<string,string> = { DRAFT:"초안", SUBMITTED:"결재 중", APPROVED:"승인 완료", POSTED:"전기 완료", REJECTED:"반려", PASSED:"검증 통과", PENDING:"미검토", REVIEWED:"검토 완료" };
const time = (value: unknown) => value ? new Date(Number(value)).toLocaleString("ko-KR", { dateStyle:"short", timeStyle:"short" }) : "—";
const won = (value: unknown) => `${Number(value ?? 0).toLocaleString("ko-KR")}원`;

export default function FinancePostingWorkspace() {
  const [data,setData]=useState<PostingData|null>(null); const [batchId,setBatchId]=useState(""); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [taxDrafts,setTaxDrafts]=useState<Record<string,{taxCodeId:string;note:string}>>({});
  const selected=useMemo(()=>data?.batches.find((row)=>String(row.id)===batchId)??null,[data,batchId]);
  async function load(nextBatchId=batchId){const response=await fetch(`/api/finance/posting-control${nextBatchId?`?batchId=${encodeURIComponent(nextBatchId)}`:""}`,{cache:"no-store"});const payload=await response.json() as PostingData&{error?:string};if(!response.ok)throw new Error(payload.error||"분개 전기 원장을 불러오지 못했습니다.");setData(payload);setBatchId(nextBatchId||payload.selectedBatchId);}
  useEffect(()=>{let cancelled=false;fetch("/api/finance/posting-control",{cache:"no-store"}).then(async(response)=>{const payload=await response.json() as PostingData&{error?:string};if(!response.ok)throw new Error(payload.error||"분개 전기 원장을 불러오지 못했습니다.");if(!cancelled){setData(payload);setBatchId(payload.selectedBatchId);}}).catch((caught)=>{if(!cancelled)setError(caught instanceof Error?caught.message:"분개 전기 원장을 불러오지 못했습니다.");});return()=>{cancelled=true;};},[]);
  async function mutate(action:string,extra:Record<string,unknown>={}){setBusy(action);setError("");setNotice("");try{const response=await fetch("/api/finance/posting-control",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,batchId,...extra})});const payload=await response.json() as PostingData&{error?:string};if(!response.ok)throw new Error(payload.error||"전기 작업을 완료하지 못했습니다.");setData(payload);setBatchId(payload.selectedBatchId);setNotice(action==="CREATE_DRAFT"?"검증 원장에서 분개 초안을 만들었습니다.":action==="REVIEW_TAX"?"세금 검토를 저장했습니다.":action==="SUBMIT"?"분개 전기 결재를 제출했습니다.":action==="POST"?"승인된 분개를 전기했습니다.":"수정분개 초안을 만들었습니다.");}catch(caught){setError(caught instanceof Error?caught.message:"전기 작업을 완료하지 못했습니다.");}finally{setBusy("");}}
  function selectBatch(id:string){setBatchId(id);void load(id).catch((caught)=>setError(caught instanceof Error?caught.message:"전기 배치를 불러오지 못했습니다."));}
  function reverse(){if(!selected)return;const reversalDate=window.prompt("수정분개 일자(YYYY-MM-DD)",new Date().toISOString().slice(0,10));if(!reversalDate)return;const reason=window.prompt("수정분개 사유를 5자 이상 입력해 주세요.","");if(!reason)return;void mutate("CREATE_REVERSAL",{reversalDate,reason});}
  const pendingTax=data?.lines.filter((line)=>String(line.tax_review_status)!=="REVIEWED").length??0;
  return <section className="data-governance-section finance-posting-control"><header><div data-korean-heading><h3>분개 초안·결재·전기</h3><span>검증된 다행 분개를 세금 검토하고, 열린 기간에서 결재 후 명시적으로 전기합니다.</span></div><div className="finance-posting-badges"><em>금액 수정 금지</em><em>마감월 차단</em><em>수정분개만 허용</em></div></header>
    {error&&<div className="data-governance-message error">{error}</div>}{notice&&<div className="data-governance-message">{notice}</div>}
    <div className="finance-posting-candidates"><strong>전기 초안 후보</strong>{data?.candidates.map((row)=><article key={String(row.id)}><div><em>{statusLabels[String(row.status)]}</em><b>{String(row.file_name)}</b><span>{String(row.source_name)} · {Number(row.row_count)}행 · 차변/대변 {won(row.total_debit)}</span><small>{time(row.created_at)}</small></div>{row.posting_batch_id?<button type="button" onClick={()=>selectBatch(String(row.posting_batch_id))}>배치 보기</button>:<button type="button" disabled={Boolean(busy)} onClick={()=>void mutate("CREATE_DRAFT",{validationId:row.id})}>분개 초안 생성</button>}</article>)}{!data?.candidates.length&&<p>검증을 통과한 분개장 후보가 없습니다. 먼저 재무 파일 매핑·균형검증을 완료하세요.</p>}</div>
    <div className="finance-posting-layout"><aside><header><strong>전기 배치</strong><button type="button" onClick={()=>void load()}>새로고침</button></header>{data?.batches.map((row)=><button type="button" key={String(row.id)} className={String(row.id)===batchId?"active":""} onClick={()=>selectBatch(String(row.id))}><em>{statusLabels[String(row.status)]??row.status}</em><b>{String(row.batch_number)}</b><span>{String(row.period_from)}~{String(row.period_to)} · {Number(row.voucher_count)}전표</span><small>{time(row.created_at)}</small></button>)}{!data?.batches.length&&<p>생성된 전기 배치가 없습니다.</p>}</aside>
      <main>{selected?<><div className="finance-posting-head"><div><em>{statusLabels[String(selected.status)]??selected.status}</em><h4>{String(selected.batch_number)}</h4><span>{String(selected.source_type)==="REVERSAL"?"수정분개":"파일 가져오기"} · {String(selected.file_name||"원전표 연결")} · {String(selected.period_from)}~{String(selected.period_to)}</span></div><dl><div><dt>전표</dt><dd>{Number(selected.voucher_count)}건</dd></div><div><dt>분개</dt><dd>{Number(selected.line_count)}행</dd></div><div><dt>차변</dt><dd>{won(selected.total_debit)}</dd></div><div><dt>대변</dt><dd>{won(selected.total_credit)}</dd></div><div><dt>세금 미검토</dt><dd>{pendingTax}행</dd></div></dl><div>{String(selected.status)==="DRAFT"&&<button type="button" disabled={Boolean(busy)||pendingTax>0} onClick={()=>void mutate("SUBMIT")}>전기 결재 제출</button>}{String(selected.status)==="APPROVED"&&<button type="button" disabled={Boolean(busy)} onClick={()=>void mutate("POST")}>승인본 전기</button>}{String(selected.status)==="POSTED"&&String(selected.source_type)!=="REVERSAL"&&<button type="button" disabled={Boolean(busy)} onClick={reverse}>수정분개 생성</button>}</div></div>
        <div className="finance-posting-vouchers">{data?.vouchers.map((voucher)=><article key={String(voucher.id)}><div><strong>{String(voucher.voucher_number||voucher.source_voucher_key)}</strong><small>{String(voucher.voucher_date)} · {String(voucher.description||"적요 없음")}</small></div><span>{Number(voucher.line_count)}행</span><b>차 {won(voucher.total_debit)}</b><b>대 {won(voucher.total_credit)}</b><em>{Number(voucher.total_debit)===Number(voucher.total_credit)?"일치":"불일치"}</em></article>)}</div>
        <div className="finance-posting-lines"><div className="finance-posting-line head"><span>전표·행</span><span>계정·적요</span><span>차변</span><span>대변</span><span>세금 검토</span></div>{data?.lines.map((line)=>{const draft=taxDrafts[String(line.id)]??{taxCodeId:String(line.tax_code_id||""),note:String(line.tax_review_note||"")};return <div className="finance-posting-line" key={String(line.id)}><p><strong>{String(line.voucher_number||line.source_voucher_key)}</strong><small>{String(line.voucher_date)} · {Number(line.line_number)}행</small></p><p><strong>{String(line.account_code)} · {String(line.account_name)}</strong><small>{String(line.description||line.partner_name||"—")}</small></p><b>{Number(line.debit_amount)?won(line.debit_amount):"—"}</b><b>{Number(line.credit_amount)?won(line.credit_amount):"—"}</b><div><select disabled={String(selected.status)!=="DRAFT"} value={draft.taxCodeId} onChange={(event)=>setTaxDrafts({...taxDrafts,[String(line.id)]:{...draft,taxCodeId:event.target.value}})}><option value="">해당 없음</option>{data.taxCodes.map((tax)=><option value={String(tax.id)} key={String(tax.id)}>{String(tax.code)} · {String(tax.name)}</option>)}</select><input disabled={String(selected.status)!=="DRAFT"} value={draft.note} placeholder="검토 근거" onChange={(event)=>setTaxDrafts({...taxDrafts,[String(line.id)]:{...draft,note:event.target.value}})}/>{String(selected.status)==="DRAFT"?<button type="button" disabled={Boolean(busy)} onClick={()=>void mutate("REVIEW_TAX",{lineId:line.id,...draft})}>{String(line.tax_review_status)==="REVIEWED"?"재검토 저장":"검토 완료"}</button>:<em>{statusLabels[String(line.tax_review_status)]}</em>}</div></div>;})}</div>
        <div className="finance-posting-events"><strong>전기 이력</strong>{data?.events.map((event)=><p key={String(event.id)}><em>{String(event.action)}</em><span>{String(event.note)}</span><time>{time(event.created_at)}</time></p>)}</div></>:<div className="data-governance-empty">전기 배치를 선택하면 전표·분개·세금검토·승인 이력을 확인할 수 있습니다.</div>}</main></div>
  </section>;
}
