"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Policy = { id: string; name: string; version: number; priority: string; firstResponseHours: number; resolutionHours: number; effectiveFrom: string; effectiveTo: string; status: string };
type CaseEvent = { id: string; eventType: string; note: string; actorName: string; createdAt: number };
type ReturnLine = { id: string; deliveryLineId: string; quantity: number; disposition: string; inventoryMovementId: string; receivedAt: number | null; description: string; catalogCode: string; catalogName: string; deliveredQuantity: number };
type ServiceDocument = { id: string; category: string; version: number; fileName: string; downloadUrl: string };
type ServiceCase = { id: string; caseNumber: string; accountName: string; opportunityTitle: string; deliveryDocumentId: string; deliveryNumber: string;
  deliveryAmount: number; contractNumber: string; contactName: string; category: string; priority: string; subject: string; description: string;
  policyId: string; openedAt: number; firstResponseDueAt: number; resolutionDueAt: number; firstRespondedAt: number | null; status: string;
  ownerName: string; resolutionType: string; resolutionNote: string; refundAmount: number; financeRequestId: string; financeStatus: string;
  exchangeTaskStatus: string; events: CaseEvent[]; returnLines: ReturnLine[]; documents: ServiceDocument[] };
type Delivery = { id: string; documentNumber: string; amount: number; issuedDate: string; accountId: string; accountName: string; opportunityTitle: string;
  contractNumber: string; lines: Array<{ id: string; description: string; quantity: number; unit: string; unitPrice: number; catalogCode: string; catalogName: string }> };
type Data = { policies: Policy[]; cases: ServiceCase[]; deliveries: Delivery[];
  employees: Array<{ employeeId: string; name: string; position: string }>; contacts: Array<{ id: string; accountId: string; name: string; title: string }>;
  products: Array<{ id: string; sku: string; name: string; unit: string }>; warehouses: Array<{ id: string; code: string; name: string }> };

const categoryLabels: Record<string, string> = { INQUIRY: "문의", DEFECT: "하자", RETURN: "반품", EXCHANGE: "교환", REFUND: "환불" };
const priorityLabels: Record<string, string> = { LOW: "낮음", NORMAL: "보통", HIGH: "높음", CRITICAL: "긴급" };
const statusLabels: Record<string, string> = { OPEN: "접수", IN_PROGRESS: "처리 중", RESOLUTION_SUBMITTED: "처리안 결재 중", RESOLUTION_APPROVED: "후속 처리", RESOLVED: "해결", CLOSED: "종결", CANCELLED: "취소" };
const resolutionLabels: Record<string, string> = { NO_ACTION: "안내 완료", REPAIR: "수리", RETURN: "반품", EXCHANGE: "교환", REFUND: "환불", CREDIT: "차감·크레딧" };
const dispositionLabels: Record<string, string> = { RESTOCK: "정상 재입고", QUARANTINE: "검사 격리", SCRAP: "폐기", RETURN_TO_VENDOR: "공급사 반송" };
const money = (value: number) => `₩${value.toLocaleString("ko-KR")}`;
const localDate = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); };

export default function SalesServiceManagement({ refreshKey = 0 }: { refreshKey?: number }) {
  const [currentTime] = useState(Date.now); const [currentDate] = useState(localDate);
  const [data, setData] = useState<Data | null>(null); const [selectedId, setSelectedId] = useState("");
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  const [policy, setPolicy] = useState({ name: "", priority: "NORMAL", firstResponseHours: "", resolutionHours: "", effectiveFrom: currentDate, effectiveTo: "" });
  const [draft, setDraft] = useState({ deliveryDocumentId: "", contactId: "", category: "INQUIRY", priority: "NORMAL", subject: "", description: "", ownerEmployeeId: "", firstResponseDueAt: "", resolutionDueAt: "" });
  const [note, setNote] = useState({ text: "", firstResponse: false });
  const [returnDraft, setReturnDraft] = useState({ deliveryLineId: "", quantity: "", disposition: "RESTOCK" });
  const [resolution, setResolution] = useState({ resolutionType: "NO_ACTION", resolutionNote: "", refundAmount: "0" });
  const [receipt, setReceipt] = useState({ productId: "", warehouseId: "", movementDate: currentDate, unitCost: "" });

  async function load() {
    try {
      const response = await fetch("/api/sales/service"); const result = await response.json() as Data & { error?: string };
      if (!response.ok) throw new Error(result.error || "고객지원 데이터를 불러오지 못했습니다."); setData(result);
      const nextId = result.cases.some((item) => item.id === selectedId) ? selectedId : result.cases[0]?.id || ""; setSelectedId(nextId);
      setDraft((current) => ({ ...current, deliveryDocumentId: current.deliveryDocumentId || result.deliveries[0]?.id || "", ownerEmployeeId: current.ownerEmployeeId || result.employees[0]?.employeeId || "" }));
      setReceipt((current) => ({ ...current, productId: current.productId || result.products[0]?.id || "", warehouseId: current.warehouseId || result.warehouses[0]?.id || "" }));
    } catch (error) { setMessage(error instanceof Error ? error.message : "고객지원 데이터를 불러오지 못했습니다."); }
  }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [refreshKey]);

  async function mutate(payload: Record<string, unknown>, success: string) {
    setBusy(String(payload.action ?? "working")); setMessage("");
    try {
      const response = await fetch("/api/sales/service", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json() as { error?: string; id?: string };
      if (!response.ok) throw new Error(result.error || "고객지원 작업을 처리하지 못했습니다.");
      if (result.id) setSelectedId(result.id); await load(); setMessage(success); return true;
    } catch (error) { setMessage(error instanceof Error ? error.message : "고객지원 작업을 처리하지 못했습니다."); return false; }
    finally { setBusy(""); }
  }
  async function createPolicy(event: FormEvent) { event.preventDefault(); if (await mutate({ action: "CREATE_POLICY", ...policy, firstResponseHours: Number(policy.firstResponseHours), resolutionHours: Number(policy.resolutionHours) }, "SLA 정책 초안을 만들었습니다.")) setPolicy((current) => ({ ...current, name: "", firstResponseHours: "", resolutionHours: "" })); }
  async function createCase(event: FormEvent) { event.preventDefault(); if (await mutate({ action: "CREATE_CASE", ...draft }, "고객지원 케이스를 접수했습니다.")) setDraft((current) => ({ ...current, subject: "", description: "", firstResponseDueAt: "", resolutionDueAt: "" })); }
  async function addNote(event: FormEvent) { event.preventDefault(); if (!selectedId) return; if (await mutate({ action: "ADD_NOTE", caseId: selectedId, note: note.text, firstResponse: note.firstResponse }, note.firstResponse ? "최초응답을 기록했습니다." : "처리 메모를 추가했습니다.")) setNote({ text: "", firstResponse: false }); }
  async function addReturnLine(event: FormEvent) { event.preventDefault(); if (!selectedId) return; if (await mutate({ action: "ADD_RETURN_LINE", caseId: selectedId, deliveryLineId: returnDraft.deliveryLineId, quantity: Number(returnDraft.quantity), disposition: returnDraft.disposition }, "반품 대상행을 등록했습니다.")) setReturnDraft((current) => ({ ...current, deliveryLineId: "", quantity: "" })); }
  async function removeReturnLine(lineId: string) { await mutate({ action: "REMOVE_RETURN_LINE", lineId }, "반품 대상행을 제거했습니다."); }
  async function submitResolution(event: FormEvent) { event.preventDefault(); if (!selectedId) return; await mutate({ action: "SUBMIT_RESOLUTION", caseId: selectedId, ...resolution, refundAmount: Number(resolution.refundAmount) }, "처리안을 전자결재로 제출했습니다."); }
  async function upload(file?: File) {
    if (!selectedId || !file) return; setBusy("upload"); setMessage("");
    try {
      const form = new FormData(); form.append("module", "sales"); form.append("entityType", "salesServiceCase"); form.append("entityId", selectedId); form.append("category", "SERVICE_EVIDENCE"); form.append("file", file);
      const response = await fetch("/api/documents", { method: "POST", body: form }); const result = await response.json() as { error?: string };
      if (!response.ok) throw new Error(result.error || "근거문서를 저장하지 못했습니다."); await load(); setMessage("처리 근거문서를 저장했습니다.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "근거문서를 저장하지 못했습니다."); } finally { setBusy(""); }
  }
  async function postReceipt(line: ReturnLine) { await mutate({ action: "POST_RETURN_RECEIPT", lineId: line.id, ...receipt, unitCost: Number(receipt.unitCost) }, "승인 반품을 재고에 입고했습니다."); }
  async function closeCase() { if (!selectedId) return; const closureNote = window.prompt("종결 확인 내용을 5자 이상 입력해 주세요.", "승인 후속조치 완료 확인"); if (closureNote) await mutate({ action: "CLOSE_CASE", caseId: selectedId, closureNote }, "고객지원 케이스를 종결했습니다."); }
  async function cancelCase() { if (!selectedId) return; const reason = window.prompt("취소 사유를 5자 이상 입력해 주세요.", "중복 또는 오접수"); if (reason) await mutate({ action: "CANCEL_CASE", caseId: selectedId, reason }, "고객지원 케이스를 취소했습니다."); }

  const selected = data?.cases.find((item) => item.id === selectedId) ?? null;
  const selectedDelivery = data?.deliveries.find((item) => item.id === (selected?.deliveryDocumentId || draft.deliveryDocumentId));
  const activePolicy = data?.policies.find((item) => item.status === "ACTIVE" && item.priority === draft.priority);
  const selectedDeliveryForDraft = data?.deliveries.find((item) => item.id === draft.deliveryDocumentId);
  const availableContacts = data?.contacts.filter((item) => item.accountId === selectedDeliveryForDraft?.accountId) ?? [];
  const openCount = data?.cases.filter((item) => ["OPEN", "IN_PROGRESS"].includes(item.status)).length ?? 0;
  const responseOverdue = data?.cases.filter((item) => ["OPEN", "IN_PROGRESS"].includes(item.status) && !item.firstRespondedAt && item.firstResponseDueAt < currentTime).length ?? 0;
  const resolutionOverdue = data?.cases.filter((item) => !["CLOSED", "CANCELLED", "RESOLVED"].includes(item.status) && item.resolutionDueAt < currentTime).length ?? 0;
  const pendingAction = data?.cases.filter((item) => item.status === "RESOLUTION_APPROVED").length ?? 0;
  const policyById = useMemo(() => new Map((data?.policies ?? []).map((item) => [item.id, item])), [data]);

  return <section className="panel sales-service-management">
    <header><div data-korean-heading><h2>고객지원·반품 관리</h2><span>확정 납품 이후 문의, 하자, 반품, 교환, 환불을 SLA와 승인 절차로 관리합니다.</span></div><strong>{data?.cases.length ?? 0}건</strong></header>
    {message && <div className="sales-contract-message" role="status">{message}</div>}
    <div className="sales-service-metrics"><article><small>처리 중</small><strong>{openCount}건</strong><span>접수·진행</span></article><article className={responseOverdue ? "warning" : ""}><small>최초응답 지연</small><strong>{responseOverdue}건</strong><span>SLA 기한 기준</span></article><article className={resolutionOverdue ? "warning" : ""}><small>해결기한 경과</small><strong>{resolutionOverdue}건</strong><span>미종결 기준</span></article><article className={pendingAction ? "warning" : ""}><small>승인 후속 처리</small><strong>{pendingAction}건</strong><span>재입고·환불·교환</span></article></div>
    <details className="sales-service-policy"><summary>SLA 정책 관리</summary><form onSubmit={createPolicy}><label>정책명<input required minLength={2} value={policy.name} onChange={(event) => setPolicy({ ...policy, name: event.target.value })} /></label><label>우선순위<select value={policy.priority} onChange={(event) => setPolicy({ ...policy, priority: event.target.value })}>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>최초응답 시간<input required type="number" min="1" max="8760" value={policy.firstResponseHours} onChange={(event) => setPolicy({ ...policy, firstResponseHours: event.target.value })} /></label><label>해결 시간<input required type="number" min="1" max="8760" value={policy.resolutionHours} onChange={(event) => setPolicy({ ...policy, resolutionHours: event.target.value })} /></label><label>적용 시작<input required type="date" value={policy.effectiveFrom} onChange={(event) => setPolicy({ ...policy, effectiveFrom: event.target.value })} /></label><label>적용 종료<input type="date" value={policy.effectiveTo} onChange={(event) => setPolicy({ ...policy, effectiveTo: event.target.value })} /></label><button disabled={Boolean(busy)} type="submit">+ 정책 초안</button></form><div>{data?.policies.map((item) => <p key={item.id}><span>{item.name} v{item.version} · {priorityLabels[item.priority]}</span><strong>{item.firstResponseHours}h / {item.resolutionHours}h</strong><em>{item.status}</em>{item.status === "DRAFT" && <button type="button" onClick={() => void mutate({ action: "SUBMIT_POLICY", id: item.id }, "SLA 정책을 전자결재로 제출했습니다.")}>결재 제출</button>}</p>)}</div></details>
    <form className="sales-service-create" onSubmit={createCase}><h3>고객 이슈 접수</h3><label>확정 납품<select required value={draft.deliveryDocumentId} onChange={(event) => setDraft({ ...draft, deliveryDocumentId: event.target.value, contactId: "" })}><option value="">선택</option>{data?.deliveries.map((item) => <option key={item.id} value={item.id}>{item.documentNumber} · {item.accountName} · {money(item.amount)}</option>)}</select></label><label>고객 담당자<select value={draft.contactId} onChange={(event) => setDraft({ ...draft, contactId: event.target.value })}><option value="">미지정</option>{availableContacts.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.title}</option>)}</select></label><label>유형<select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })}>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>우선순위<select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value })}>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>담당자<select required value={draft.ownerEmployeeId} onChange={(event) => setDraft({ ...draft, ownerEmployeeId: event.target.value })}><option value="">선택</option>{data?.employees.map((item) => <option key={item.employeeId} value={item.employeeId}>{item.name} · {item.position}</option>)}</select></label><label>제목<input required minLength={3} value={draft.subject} onChange={(event) => setDraft({ ...draft, subject: event.target.value })} /></label><label className="wide">접수 내용<textarea required minLength={10} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label>{!activePolicy && <><label>최초응답 기한<input required type="datetime-local" value={draft.firstResponseDueAt} onChange={(event) => setDraft({ ...draft, firstResponseDueAt: event.target.value })} /></label><label>해결 기한<input required type="datetime-local" value={draft.resolutionDueAt} onChange={(event) => setDraft({ ...draft, resolutionDueAt: event.target.value })} /></label></>}<p className="sales-service-policy-hint">{activePolicy ? `${activePolicy.name} v${activePolicy.version}: ${activePolicy.firstResponseHours}시간 내 응답 · ${activePolicy.resolutionHours}시간 내 해결` : "활성 SLA가 없어 두 기한을 직접 입력해야 합니다."}</p><button disabled={Boolean(busy) || !data?.deliveries.length} type="submit">+ 케이스 접수</button></form>
    <div className="sales-service-layout"><aside>{data?.cases.map((item) => <button type="button" className={item.id === selectedId ? "selected" : ""} onClick={() => setSelectedId(item.id)} key={item.id}><span>{item.caseNumber} · {categoryLabels[item.category]}</span><strong>{item.subject}</strong><small>{item.accountName} · {item.ownerName}</small><em className={item.status.toLowerCase()}>{statusLabels[item.status]}</em></button>)}{!data?.cases.length && <p>접수된 고객 이슈가 없습니다.</p>}</aside>
      {selected ? <div className="sales-service-detail"><header><div><p>{selected.deliveryNumber} · {selected.accountName}</p><h3>{selected.caseNumber} {selected.subject}</h3><span>{categoryLabels[selected.category]} · {priorityLabels[selected.priority]} · 담당 {selected.ownerName}</span></div><em className={selected.status.toLowerCase()}>{statusLabels[selected.status]}</em></header>
        <div className="sales-service-facts"><p><small>계약</small><strong>{selected.contractNumber || "미연결"}</strong></p><p><small>고객 담당자</small><strong>{selected.contactName || "미지정"}</strong></p><p className={!selected.firstRespondedAt && selected.firstResponseDueAt < currentTime ? "overdue" : ""}><small>최초응답 기한</small><strong>{new Date(selected.firstResponseDueAt).toLocaleString("ko-KR")}</strong></p><p className={selected.resolutionDueAt < currentTime && !["RESOLVED", "CLOSED"].includes(selected.status) ? "overdue" : ""}><small>해결 기한</small><strong>{new Date(selected.resolutionDueAt).toLocaleString("ko-KR")}</strong></p><p><small>SLA 정책</small><strong>{policyById.get(selected.policyId)?.name || "수동 기한"}</strong></p><p><small>환불 후속</small><strong>{selected.refundAmount ? `${money(selected.refundAmount)} · ${selected.financeStatus || "지급요청 미생성"}` : "없음"}</strong></p></div>
        {["OPEN", "IN_PROGRESS"].includes(selected.status) && <><div className="sales-service-actions"><form onSubmit={addNote}><textarea required minLength={3} value={note.text} onChange={(event) => setNote({ ...note, text: event.target.value })} placeholder="고객 응답 또는 내부 처리 메모" /><label><input type="checkbox" checked={note.firstResponse} disabled={Boolean(selected.firstRespondedAt)} onChange={(event) => setNote({ ...note, firstResponse: event.target.checked })} />최초 고객 응답</label><button disabled={Boolean(busy)} type="submit">기록 추가</button></form><label className="file-action">처리 근거 첨부<input type="file" accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg,.txt,.csv" onChange={(event) => { void upload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label><button type="button" className="danger" onClick={() => void cancelCase()}>접수 취소</button></div>
          {["RETURN", "EXCHANGE", "REFUND"].includes(selected.category) && <form className="sales-service-return-form" onSubmit={addReturnLine}><h4>대상 납품행</h4><label>납품 품목<select required value={returnDraft.deliveryLineId} onChange={(event) => setReturnDraft({ ...returnDraft, deliveryLineId: event.target.value })}><option value="">선택</option>{selectedDelivery?.lines.map((line) => <option key={line.id} value={line.id}>{line.catalogCode || "품목"} · {line.catalogName || line.description} · {line.quantity} {line.unit}</option>)}</select></label><label>처리 수량<input required type="number" min="0.001" step="0.001" value={returnDraft.quantity} onChange={(event) => setReturnDraft({ ...returnDraft, quantity: event.target.value })} /></label><label>처리 방식<select value={returnDraft.disposition} onChange={(event) => setReturnDraft({ ...returnDraft, disposition: event.target.value })}>{Object.entries(dispositionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button disabled={Boolean(busy)} type="submit">+ 대상 추가</button></form>}
          <form className="sales-service-resolution" onSubmit={submitResolution}><h4>처리안 결재</h4><label>처리 유형<select value={resolution.resolutionType} onChange={(event) => setResolution({ ...resolution, resolutionType: event.target.value })}>{Object.entries(resolutionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>환불금액<input type="number" min="0" max={selected.deliveryAmount} value={resolution.refundAmount} onChange={(event) => setResolution({ ...resolution, refundAmount: event.target.value })} /></label><label className="wide">처리 근거<textarea required minLength={10} value={resolution.resolutionNote} onChange={(event) => setResolution({ ...resolution, resolutionNote: event.target.value })} /></label><button disabled={Boolean(busy) || !selected.firstRespondedAt || !selected.documents.length} type="submit">전자결재 제출</button></form></>}
        <div className="sales-service-return-ledger"><h4>반품·교환·환불 대상</h4>{selected.returnLines.map((line) => <div key={line.id}><p><strong>{line.catalogCode || "품목"} · {line.catalogName || line.description}</strong><small>{line.quantity} · {dispositionLabels[line.disposition]}</small></p><div className="sales-service-line-state"><em>{line.inventoryMovementId ? "재입고 완료" : line.disposition === "RESTOCK" ? "재입고 대기" : "후속 업무 확인"}</em>{["OPEN", "IN_PROGRESS"].includes(selected.status) && <button type="button" onClick={() => void removeReturnLine(line.id)}>제거</button>}</div>{selected.status === "RESOLUTION_APPROVED" && line.disposition === "RESTOCK" && !line.inventoryMovementId && <div className="sales-service-receipt"><select value={receipt.productId} onChange={(event) => setReceipt({ ...receipt, productId: event.target.value })}><option value="">재고 상품</option>{data?.products.map((item) => <option key={item.id} value={item.id}>{item.sku} · {item.name}</option>)}</select><select value={receipt.warehouseId} onChange={(event) => setReceipt({ ...receipt, warehouseId: event.target.value })}><option value="">창고</option>{data?.warehouses.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><input aria-label="반품 입고일" type="date" value={receipt.movementDate} onChange={(event) => setReceipt({ ...receipt, movementDate: event.target.value })} /><input aria-label="실제 재입고 단가" type="number" min="1" placeholder="실제 단가" value={receipt.unitCost} onChange={(event) => setReceipt({ ...receipt, unitCost: event.target.value })} /><button type="button" onClick={() => void postReceipt(line)}>재고 입고</button></div>}</div>)}{!selected.returnLines.length && <p>등록된 대상행이 없습니다.</p>}</div>
        <div className="sales-service-documents"><h4>처리 근거</h4>{selected.documents.map((document) => <a key={document.id} href={document.downloadUrl}>{document.fileName} · v{document.version}</a>)}{!selected.documents.length && <p>첨부된 근거문서가 없습니다.</p>}</div>
        <div className="sales-service-timeline"><h4>처리 이력</h4>{selected.events.map((event) => <article key={event.id}><time>{new Date(event.createdAt).toLocaleString("ko-KR")}</time><strong>{event.eventType}</strong><span>{event.actorName}</span><p>{event.note}</p></article>)}</div>
        {["RESOLUTION_APPROVED", "RESOLVED"].includes(selected.status) && <button className="sales-service-close" type="button" onClick={() => void closeCase()}>후속조치 확인 후 종결</button>}
      </div> : <div className="finance-empty">왼쪽에서 고객지원 케이스를 선택해 주세요.</div>}
    </div>
  </section>;
}
