"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Course = { id: string; title: string; courseType: string; year: number; description: string; provider: string; deliveryMode: string; startDate: string; dueDate: string; durationMinutes: number; audienceType: string; organizationId: string; status: string };
type Assignment = { id: string; courseId: string; employeeId: string; employeeName: string; department: string; status: string; progress: number; score: number | null; completedMinutes: number; evidenceName: string; evidenceRef: string; employeeNote: string; waiverReason: string; verifiedBy: string; verifiedAt: number | null; completedAt: number | null };
type Data = { principal: { employeeId: string; employeeName: string }; canAdmin: boolean; courses: Course[]; selected: Course | null; assignments: Assignment[]; organizations: { id: string; name: string }[]; summary: { total: number; completed: number; incomplete: number; completionRate: number; overdue: number }; error?: string };

const courseTypeLabels: Record<string, string> = { MANDATORY: "법정교육", ROLE: "직책교육", SKILL: "직무교육" };
const statusLabels: Record<string, string> = { DRAFT: "초안", OPEN: "진행 중", CLOSED: "종료", ASSIGNED: "미시작", IN_PROGRESS: "진행 중", SUBMITTED: "증빙 검토 대기", COMPLETED: "수료", WAIVED: "면제" };

async function fetchTraining(courseId = "") {
  const response = await fetch(`/api/hr/training${courseId ? `?courseId=${encodeURIComponent(courseId)}` : ""}`);
  const payload = await response.json() as Data;
  if (!response.ok) throw new Error(payload.error || "교육 자료를 불러오지 못했습니다.");
  return payload;
}

function AssignmentEditor({ assignment, course, canAdmin, isSelf, onSaved, onNotify }: { assignment: Assignment; course: Course; canAdmin: boolean; isSelf: boolean; onSaved: () => void; onNotify: (message: string) => void }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [draft, setDraft] = useState({ progress: assignment.progress, completedMinutes: assignment.completedMinutes, score: assignment.score === null ? "" : String(assignment.score), evidenceName: assignment.evidenceName, evidenceRef: assignment.evidenceRef, employeeNote: assignment.employeeNote });
  const editable = course.status === "OPEN" && !["SUBMITTED", "COMPLETED", "WAIVED"].includes(assignment.status) && (canAdmin || isSelf);
  async function save() {
    setSaving(true); const response = await fetch("/api/hr/training", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "UPDATE_ASSIGNMENT", courseId: course.id, assignmentId: assignment.id, ...draft }) });
    const payload = await response.json() as { error?: string }; setSaving(false);
    if (!response.ok) { onNotify(payload.error || "교육 이수 정보를 저장하지 못했습니다."); return; }
    onNotify("교육 진행·증빙 정보를 저장했습니다."); setOpen(false); onSaved();
  }
  async function waive() {
    const reason = window.prompt("면제 사유를 10자 이상 입력하세요."); if (!reason || reason.trim().length < 10) { onNotify("면제 사유를 10자 이상 입력해 주세요."); return; }
    setSaving(true); const response = await fetch("/api/hr/training", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "WAIVE_ASSIGNMENT", courseId: course.id, assignmentId: assignment.id, reason }) });
    const payload = await response.json() as { error?: string }; setSaving(false); if (!response.ok) { onNotify(payload.error || "면제 처리하지 못했습니다."); return; }
    onNotify("교육 대상자를 사유와 함께 면제 처리했습니다."); onSaved();
  }
  async function verify() {
    setSaving(true); const response = await fetch("/api/hr/training", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "VERIFY_ASSIGNMENT", courseId: course.id, assignmentId: assignment.id }) });
    const payload = await response.json() as { error?: string }; setSaving(false); if (!response.ok) { onNotify(payload.error || "수료 확정하지 못했습니다."); return; }
    onNotify("교육 증빙을 확인하고 수료 확정했습니다."); onSaved();
  }
  return <article className={`training-assignment ${assignment.status.toLowerCase()}`}><button type="button" className="training-assignment-head" onClick={() => editable && setOpen((value) => !value)}><span>{assignment.employeeName.slice(0, 1)}</span><div><strong>{assignment.employeeName}</strong><small>{assignment.department} · {assignment.completedMinutes}분</small></div><em>{assignment.progress}%</em><b>{statusLabels[assignment.status] ?? assignment.status}</b></button>{assignment.evidenceName && <p className="training-evidence">증빙 · {assignment.evidenceName} ({assignment.evidenceRef})</p>}{assignment.waiverReason && <p className="training-evidence">면제 사유 · {assignment.waiverReason}</p>}{canAdmin && assignment.status === "SUBMITTED" && <div className="training-verification"><span>제출된 증빙을 확인한 뒤 수료를 확정하세요.</span><button type="button" disabled={saving} onClick={verify}>증빙 확인·수료 확정</button></div>}{open && <div className="training-assignment-form"><label>진행률<input type="number" min="0" max="100" value={draft.progress} onChange={(event) => setDraft({ ...draft, progress: Number(event.target.value) })} /></label><label>이수시간(분)<input type="number" min="0" value={draft.completedMinutes} onChange={(event) => setDraft({ ...draft, completedMinutes: Number(event.target.value) })} /></label><label>점수<input type="number" min="0" max="100" value={draft.score} onChange={(event) => setDraft({ ...draft, score: event.target.value })} /></label><label>증빙명<input value={draft.evidenceName} onChange={(event) => setDraft({ ...draft, evidenceName: event.target.value })} placeholder="수료증 또는 교육결과" /></label><label className="wide">증빙 참조<input value={draft.evidenceRef} onChange={(event) => setDraft({ ...draft, evidenceRef: event.target.value })} placeholder="문서 ID 또는 보관 경로" /></label><label className="wide">학습 메모<textarea value={draft.employeeNote} onChange={(event) => setDraft({ ...draft, employeeNote: event.target.value })} /></label><button type="button" disabled={saving} onClick={save}>진행·증빙 제출</button>{canAdmin && <button type="button" className="secondary-button" disabled={saving} onClick={waive}>사유 입력 후 면제</button>}</div>}</article>;
}

export default function TrainingManagementView({ onNotify }: { onNotify: (message: string) => void }) {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [createOpen, setCreateOpen] = useState(false);
  const [draft, setDraft] = useState({ title: "", courseType: "MANDATORY", year: 2026, description: "", provider: "", deliveryMode: "ONLINE", startDate: "2026-08-14", dueDate: "2026-08-31", durationMinutes: 60, audienceType: "ALL", organizationId: "" });
  const load = useCallback(async (courseId = "") => { setLoading(true); try { setData(await fetchTraining(courseId)); } catch (error) { onNotify(error instanceof Error ? error.message : "교육 자료를 불러오지 못했습니다."); } finally { setLoading(false); } }, [onNotify]);
  useEffect(() => { let cancelled = false; fetchTraining().then((next) => { if (!cancelled) setData(next); }).catch((error: Error) => { if (!cancelled) onNotify(error.message); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [onNotify]);
  const selected = data?.selected ?? null;
  const byDepartment = useMemo(() => (data?.assignments ?? []).reduce<Record<string, Assignment[]>>((acc, item) => { (acc[item.department || "미지정"] ??= []).push(item); return acc; }, {}), [data]);
  async function mutate(body: Record<string, unknown>, message: string) { setBusy(true); const response = await fetch("/api/hr/training", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string; id?: string }; setBusy(false); if (!response.ok) { onNotify(payload.error || "교육 작업을 처리하지 못했습니다."); return false; } onNotify(message); await load(payload.id ?? selected?.id ?? ""); return true; }
  async function createCourse(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (await mutate({ action: "CREATE_COURSE", ...draft }, "교육 과정 초안을 만들었습니다.")) { setCreateOpen(false); setDraft({ ...draft, title: "", description: "", provider: "" }); } }
  return <div className="page-wrap module-page training-page"><section className="module-hero"><div data-korean-heading><h1>교육 및 법정교육</h1><p>대상자 배정부터 수료 증빙, 면제와 미이수 알림까지 실제 원장으로 관리합니다.</p></div><div className="training-hero-actions">{data?.courses.length ? <select value={selected?.id ?? ""} onChange={(event) => void load(event.target.value)}>{data.courses.map((course) => <option key={course.id} value={course.id}>{course.year} · {course.title}</option>)}</select> : null}{data?.canAdmin && <button type="button" className="primary-button" onClick={() => setCreateOpen((value) => !value)}>+ 교육 과정 등록</button>}</div></section>
    {createOpen && <form className="panel training-course-form" onSubmit={createCourse}><label>과정명<input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>구분<select value={draft.courseType} onChange={(event) => setDraft({ ...draft, courseType: event.target.value })}><option value="MANDATORY">법정교육</option><option value="ROLE">직책교육</option><option value="SKILL">직무교육</option></select></label><label>연도<input type="number" min="2024" max="2100" value={draft.year} onChange={(event) => setDraft({ ...draft, year: Number(event.target.value) })} /></label><label>교육기관<input required value={draft.provider} onChange={(event) => setDraft({ ...draft, provider: event.target.value })} /></label><label>방식<select value={draft.deliveryMode} onChange={(event) => setDraft({ ...draft, deliveryMode: event.target.value })}><option value="ONLINE">온라인</option><option value="OFFLINE">오프라인</option><option value="BLENDED">혼합</option></select></label><label>인정시간(분)<input type="number" min="1" value={draft.durationMinutes} onChange={(event) => setDraft({ ...draft, durationMinutes: Number(event.target.value) })} /></label><label>시작일<input type="date" value={draft.startDate} onChange={(event) => setDraft({ ...draft, startDate: event.target.value })} /></label><label>마감일<input type="date" value={draft.dueDate} onChange={(event) => setDraft({ ...draft, dueDate: event.target.value })} /></label><label>대상<select value={draft.audienceType} onChange={(event) => setDraft({ ...draft, audienceType: event.target.value, organizationId: event.target.value === "ALL" ? "" : draft.organizationId || data?.organizations[0]?.id || "" })}><option value="ALL">전 직원</option><option value="ORGANIZATION">특정 조직</option></select></label>{draft.audienceType === "ORGANIZATION" && <label>대상 조직<select value={draft.organizationId} onChange={(event) => setDraft({ ...draft, organizationId: event.target.value })}>{data?.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label className="wide">과정 설명<textarea required minLength={5} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><button type="submit" className="primary-button" disabled={busy}>교육 과정 초안 저장</button></form>}
    {!selected ? <section className="panel training-empty"><strong>등록된 교육 과정이 없습니다.</strong><span>HR 관리자가 과정을 만들고 개설하면 재직자가 대상으로 고정됩니다.</span></section> : <><section className="panel training-stage"><div><span>{courseTypeLabels[selected.courseType] ?? selected.courseType}</span><strong>{selected.title}</strong><small>{selected.provider} · {selected.startDate}~{selected.dueDate} · {selected.durationMinutes}분 · {statusLabels[selected.status] ?? selected.status}</small></div><div>{data?.canAdmin && selected.status === "DRAFT" && <><button type="button" disabled={busy} onClick={() => void mutate({ action: "DELETE_COURSE", courseId: selected.id }, "교육 과정 초안을 삭제했습니다.")}>초안 삭제</button><button type="button" className="primary-button" disabled={busy} onClick={() => void mutate({ action: "OPEN_COURSE", courseId: selected.id }, "재직자 스냅샷으로 교육 과정을 개설했습니다.")}>과정 개설</button></>}{data?.canAdmin && selected.status === "OPEN" && <button type="button" className="primary-button" disabled={busy || Boolean(data.summary.incomplete)} onClick={() => void mutate({ action: "CLOSE_COURSE", courseId: selected.id }, "교육 과정을 종료했습니다.")}>과정 종료</button>}</div></section>
      <section className="metric-grid module-metrics">{[["교육 대상", data?.summary.total ?? 0], ["수료·면제", data?.summary.completed ?? 0], ["이수율", `${data?.summary.completionRate ?? 0}%`], ["기한 초과", data?.summary.overdue ?? 0]].map(([label, value], index) => <div className="compact-metric" key={String(label)}><span className={`metric-accent ${["navy", "blue", "green", "orange"][index]}`}></span><p>{label}</p><h2>{value}{index < 2 || index === 3 ? <small>명</small> : null}</h2><small>교육 이수 원장 기준</small></div>)}</section>
      {selected.status === "DRAFT" ? <section className="panel training-empty"><strong>아직 대상자가 배정되지 않았습니다.</strong><span>과정을 개설하면 현재 재직자와 소속을 고정하여 이수 원장을 만듭니다.</span></section> : <section className="training-departments">{loading ? <section className="panel training-empty">불러오는 중…</section> : Object.entries(byDepartment).map(([department, items]) => <section className="panel training-department" key={department}><header><div data-korean-heading><h2>{department}</h2></div><span>{items.filter((item) => ["COMPLETED", "WAIVED"].includes(item.status)).length}/{items.length}명</span></header><div>{items.map((assignment) => <AssignmentEditor key={assignment.id} assignment={assignment} course={selected} canAdmin={Boolean(data?.canAdmin)} isSelf={assignment.employeeId === data?.principal.employeeId} onSaved={() => void load(selected.id)} onNotify={onNotify} />)}</div></section>)}</section>}
      <p className="training-control-note">교육 이수 결과는 증빙·감사 원장으로 관리되며 급여·평가·승진에 자동 반영되지 않습니다.</p></>}
  </div>;
}
